Template.home.helpers(
{
  welcome: function() {
    return 'Welcome to Meteor Generated by Yeoman!';
  },
  additional: function() {
    return 'Howdy there, future releases will include even more smart defaults.'
  },
  all: function()
  {
    return (this.params);
  }
});

Template.home.events(
{
  'click .clicky': function(event, template) {
    template.find('.clicky').innerHTML='Clicked.';
  }
});